### ISSUE TITLE
firefox

### ISSUE THREAD

**Issue by elEthamin** [Senshi111/debian-hyprland-hyprdots#3]
in  Theme/Scripts/custom_hypr.lst
you need to replace the firefox with firefox-esr
Apt can't find firefox

**Comment by Senshi111** [comment]
What do you mean? Im installing firefox from debian repo. firefox and firefox-esr are in debian repo
![230831_20h38m33s_screenshot](https://github.com/Senshi111/debian-hyprland-hyprdots/assets/40372242/92989626-ddea-422b-b982-e09ebddbd111)

**Comment by elEthamin** [comment]
mmh, on my debian12, firefox does not exist
![image](https://github.com/Senshi111/debian-hyprland-hyprdots/assets/100302330/faedd1a6-d42c-4e86-98e1-02abf7b6bfbc)

**Comment by Senshi111** [comment]
That's because Firefox is only available in debian sid repository. This is made for debian sid not for debian 12 or debian testing. I don't even know if this works on those debian versions
