### ISSUE TITLE
Cannot manage to make it work on PopOS! 

### ISSUE THREAD

**Issue by samsungapore** [Senshi111/debian-hyprland-hyprdots#4]
I think it's normal but I would have wanted it to work haha

**Comment by Senshi111** [comment]
Where you have problem? Script that builds hyprland or?

**Comment by samsungapore** [comment]
the script is running fine but in the end I don't have the possibility to switch on the newly installed user interface after reboot

**Comment by Senshi111** [comment]
I don't think i understand you. You don't have option to switch users in sddm?

**Comment by rajudev** [comment]
Facing the same issue, the session is not available for login in the list of sessions on SDDM login screen

**Comment by tellmeY18** [comment]
copy the desktop entry (examples/hyprland.desktop) to /usr/share/wayland-sessions/

I had to do this after the manual installation of Hyprland for it to show up in the desktop entries in ly login manager. Still had no issues with lightdm maybe give it a try or verify the file exists ?

**Comment by rajudev** [comment]
After a lot of debugging with @tellmeY18 , we found the compilation was failing due to wrong version of `wayland-protocols` . I had the correct version installed `1.32` on Debian unstable/sid . However it was finding 1.24

The culprit was snap using a gnome-core package which was supplying the value 1.24 of wayland-protocols to meson. 

After removing the snaps, the build completed properly and the installation went in smoothly.

**Comment by rajudev** [comment]
You can try doing the same with PopOS, or paste the logs of the scripts run and we can see what the issue is.

**Comment by Senshi111** [comment]
I will try to improve install hyprland script and add check if  build failed

**Comment by vola91** [comment]
@rajudev Hi, i m using a fresh install Debian12 with gnome, i dont have any snap packages installed (I guess?)  Could you pls share how to 'removing the snaps'? Thx

**Comment by rajudev** [comment]
> @rajudev Hi, i m using a fresh install Debian12 with gnome, i dont have any snap packages installed (I guess?) Could you pls share how to 'removing the snaps'? Thx
> 
> `wlroots| Dependency wayland-protocols found: NO found 1.24 but need: '>=1.32'`


I removed all installed snap packages using `sudo snap remove <package-name>` 
and then removed snap with `sudo apt purge snap`

**Comment by vola91** [comment]
> I removed all installed snap packages using `sudo snap remove <package-name>` and then removed snap with `sudo apt purge snap`

ok, I m sure that i dont have any snap packages in my debian12, even 'snap' is not installed. So it may be some preinstalled packages supplying 1.24. 

Thanks for reply, i'll try to dig out what's going on

**Comment by tellmeY18** [comment]
> > I removed all installed snap packages using `sudo snap remove <package-name>` and then removed snap with `sudo apt purge snap`
> 
> ok, I m sure that i dont have any snap packages in my debian12, even 'snap' is not installed. So it may be some preinstalled packages supplying 1.24. 
> 
> Thanks for reply, i'll try to dig out what's going on
> 

Hey you have to be using debian sid to get the Wayland protocols proper version. 

Hope it solves the issue.

**Comment by Senshi111** [comment]
> > > I removed all installed snap packages using `sudo snap remove <package-name>` and then removed snap with `sudo apt purge snap`
> > 
> > 
> > ok, I m sure that i dont have any snap packages in my debian12, even 'snap' is not installed. So it may be some preinstalled packages supplying 1.24.
> > Thanks for reply, i'll try to dig out what's going on
> 
> Hey you have to be using debian sid to get the Wayland protocols proper version.
> 
> Hope it solves the issue.

Even debian 12 has wayland-protocols (1.31-1) version but somehow his getting 1.24

**Comment by vola91** [comment]
@Senshi111 @tellmeY18 
Finally solve it:

1. I have already install wayland-protocols (1.31-1) from sid
    Apt is showing version: 1.32-1
    But pkg-config --modversion wayland-protocols is showing 1.24
    
2. Then i found a file here '/usr/local/share/pkgconfig/wayland-protocols.pc' is still providing 1.24

3. Remove this file and reinstall wayland-protocols by apt then solve the problem. 🦹
