### ISSUE TITLE
The script doesn't work for me

### ISSUE THREAD

**Issue by Ramy-Ashraf** [Senshi111/debian-hyprland-hyprdots#8]
After minimal debian installation and running the script, no changes happen to my system. And I don't know what happened.
Note: "I'm using debian 12"

**Comment by Senshi111** [comment]
It's not working for debian 12 because hyprland script won't build hyprland. I created this script for debian sid also some people here use debian testing and they said it works on testing as well. Hyprland required newer versions of libs and that's the problem with debian 12 and hyprland.

**Comment by Ramy-Ashraf** [comment]
Okay, thanks a lot for your response.
