### ISSUE TITLE
Impediment: libdrm - script not functional

### ISSUE THREAD

**Issue by Quvist** [Senshi111/debian-hyprland-hyprdots#9]
Hey, am I correct in understanding that Deb and(using Ubuntu 23.10) cant run the script due to an older version of libdrm?

Can an option to install  Hyprland 0.32.3 be added? Or is this functional on some test branch? 
This could use clarification in the readme.mb

**Comment by Senshi111** [comment]
This is for debian sid version.
You can get lattest libdrm for Ubuntu here that's ubuntu devel branch called noble 
https://packages.ubuntu.com/search?keywords=libdrm-dev

**Comment by Quvist** [comment]
> This is for debian sid version. You can get lattest libdrm for Ubuntu here, that's ubuntu devel branch called noble https://packages.ubuntu.com/search?keywords=libdrm-dev

Affermative. The noble version is 2.4.117, this requires atleast 2.4.118 if I'm correct. Newest Hyprland is not compatible with 117 and older. Can you confirm? If so I can close issue.

**Comment by Senshi111** [comment]
Yes you are correct. For latest hyprland it requires libdrm 2.4.118+
